num_clusters: 40

alpha_prior: [9, 1]

kappa_prior: 1

data:
  snv:
    file: examples/snv.tsv.gz
    
    gamma_prior: [[98, 1, 1],
                  [25, 50, 25],
                  [1, 1, 98]]
   
    state_prior: [1, 1, 1]
  
  breakpoint:
    file: examples/breakpoint.tsv.gz
    
    gamma_prior: [[9, 1],
                  [1, 9]]

    state_prior: [1, 1]